### ISSUE TITLE
Custom default key-value pairs

### ISSUE THREAD

**Issue by felsocim** [jm-cc/gcvb#1]
In a test definition file, it is possible to assign default values to some of **existing** key entries such as `executable`, `options` or `nprocs`.

The suggestion is to make it possible to define custom default key-value entries. For example, if in my `launch_command` I am using two different executables, I would like to be able to have two different default key-value pairs for `options` such as `options_exec1` and `options_exec2`.

**Comment by jm-cc** [comment]
Hi,

it was not really intended to work that way but I think you can just use a list (or a dict) in the *default_values* dictionary for the key that interests you. In your example *options*. Right now, I don't want to add custom default values because I am not sure how they should be treated.

Then, when using the *@job_creation* token, just add the relevant accessor (i.e. indice for the list, key if you chose a dictionary)  

See example below:
```yaml
default_values:
  task:
    nprocs: "1"
    nthreads: "1"
    options: ["default value for option","second value"]
    launch_command: "{@job_creation[executable]} {@job_creation[options][0]}"   #options[0] instead of the more classical options.
```
If it works for you, I will close the issue.
