### ISSUE TITLE
Allow to register multiple metrics for one validation (yaml input)

### ISSUE THREAD

**Issue by jm-cc** [jm-cc/gcvb#20]
Currently only one metric is associated with an executable in the *Validation* list.

An executable may generate more than one metric, it should be possible to register them on the right entry rather than creating fake entries.

today : 
```yaml
(...)
      Validations:
        - id: metric-1
          type: configuration_independent
          reference : 100
          tolerance: 0.03
          executable: actual_executable
        - id: "metric-2"
          reference: 88.3
          type: configuration_independent
          tolerance: 0.1
          executable: true # noop executable since the metric is generated with previous validation.
```
wanted :
```yaml
(...)
      Validations:
        executable : actual_executable
        metrics : 
          - {id : metric-1, reference : 100, type : configuration_independent, tolerance: 0.03}
          - {id : metric-2, reference : 88,3, type : configuration_independent, tolerance: 0.01}
 ```

Previous syntax for validation with only one metric will still be valid.

## TODO 
- [x] Implement
- [x] Example in gcvb-examples
- [ ] Write documentation
