### ISSUE TITLE
Stop a test if a task fail

### ISSUE THREAD

**Issue by jeromerobert** [jm-cc/gcvb#4]
* It would be nice if it was possible to stop a test if one of its task fail (i.e. task process exit code != 0)
* It would also be nice to do not run validation if a task fail

**Comment by jm-cc** [comment]
Here is the yaml to test the functionality. It is working only with the jobrunner and became the default behaviour in cfaefdaf02be915547ff83f512cb4c1c68f1acae .

The way things are written for now, if a validation fails, it also ends the test.

(It is necessary to create a *data* directory with *references* and *input* directories inside it to test it)
```yaml
default_values:
  task:
    nprocs: "1"
    nthreads: "1"
    launch_command: "{@job_creation[executable]} {@job_creation[options]}"

Packs:
- pack_id : "test_return_code"
  description : "a test yaml to see if tests are stopped when a return code != 0 is returned by a test"
  Tests :
  - id: "the_actual_test"
    data : ""
    description: "check that jobrunner stops test when an return code != 0 is returned"
    Tasks:
    - executable : "echo"
      options : "hello"
    - executable : "echo"
      options : "second echo"
    - executable : "false"
      options : ""
    - executable : "echo"
      options : "third echo"
  - id: "another_test"
    data : ""
    description: "this one should go until the end"
    Tasks:
    - executable : "echo"
      options : "hello, I am the second job"
    - executable : "echo"
      options : "second echo from the second job"
    - executable : "echo"
      options : "third echo from the second job"
    - executable : "echo"
      options : "this are my last words"
```
